version: "3.7"

services:
  database:
    image: postgres
    container_name: database_duo_programming_test
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api_duo_programming_test
    ports:
      - ${HTTP_PORT}:3333
    volumes:
      - .:/usr/app/api_duo_programming_test
    links:
      - database
    depends_on:
      - database
    command: >
      sh -c "npm run migrate &&
             npm run seed:questions &&
             npm run prod"
volumes:
  pgdata:
    driver: local
